### ISSUE TITLE
Spiel stürzt ab beim Speichern

### ISSUE THREAD

**Issue by briggz17** [4c65736975/FS22_ManualDischarge#19]
### Version

1.0.0.7

### Game Version

Farming Simulator 25 (1.2.1.0)

### 👣 Steps to reproduce

Habe den Mod "Manuelles Entladen" aus dem Modhub geladen und installiert. Spiel lädt, aber beim Speichern stürzt das Spiel ab - jederzeit reproduzierbar. Map: Zielonka / Single-Player.
LS25 Version 1.3
Mod Version 1.0 aus dem Modhub

**Comment by briggz17** [comment]
Kann gerne Logs zur Verfügung stellen - müsste nur wissen welche und wo die liegen.
Aber auf jeden besten DAnk für die coolen Mods overall!

**Comment by briggz17** [comment]
Folgende Modds nutze ich:
Available dlc: (Hash: 2b9007b344aa278849cd5c98c9dd136c) (Version: 1.0.0.0) pdlc_extraContentNewHollandCR11
ExtraContent: Unlocked 'CR11GOLD'
Available dlc: (Hash: a910fbe59bd919187cacbfc7b63ec5a6) (Version: 1.1.0.0) pdlc_macDonPack
Available mod: (Hash: 60096d72e4bff635e19d6864f85fc47a) (Version: 1.0.0.0) FS25_additionalFieldInfo
Available mod: (Hash: 5c4a84bc77a5932d834e55ea4887b648) (Version: 1.0.0.0) FS25_agcoIdealPack
Available mod: (Hash: 940998dd1ac44b7a5bee7761167d1ac3) (Version: 1.0.0.0) FS25_agcoSeries9700
Available mod: (Hash: e56132b0ed69ef63b88680de27db89cd) (Version: 1.0.0.0) FS25_autoTurnOffTurnLights
Available mod: (Hash: 0a9a3ac6d5a30b9a1712b7e722b4fde4) (Version: 1.0.0.0) FS25_CabView
Available mod: (Hash: 4ded317c40a45b41701bc67b6b3b2527) (Version: 1.0.0.0) FS25_claasCarat
Available mod: (Hash: 1d54714e59e62f9d02afb1af09d5b95d) (Version: 1.0.0.0) FS25_claasJaguarPack
Available mod: (Hash: 70325b700fa5c2dba89b10727b7632bf) (Version: 1.0.0.0) FS25_cultivatorFieldCreator
Available mod: (Hash: 5566e31e2130da06eb546399e3cd1fac) (Version: 1.0.0.0) FS25_DamageControl
Available mod: (Hash: 42423a5cc6d4ebbb62046e321177639d) (Version: 1.0.0.0) FS25_enhancedFillTypeCategories
Available mod: (Hash: 6590e8b512d76a00ca7acd07a3c89723) (Version: 1.1.3.1) FS25_EnhancedVehicle
Available mod: (Hash: ac00e35f8934b715b02d22df78d5343f) (Version: 1.0.0.0) FS25_farmtechFortis3000
dataS/character/playerAnimations/animations.i3d (160.33 ms)
Available mod: (Hash: 0a04834bad837cb5a8becaf1a395d3e8) (Version: 1.0.0.1) FS25_fendtFarmConPack
dataS/character/playerAnimations/animationsVehicleCharacter.i3d (1.80 ms)
Available mod: (Hash: 48cce320122953cfb5eecafb948269f6) (Version: 1.0.0.0) FS25_FrontCultivator
Available mod: (Hash: 640bc45e40a6c744755e1112f54b9b12) (Version: 1.0.0.0) FS25_FuelLevelWarning
Available mod: (Hash: eedaf5e1a5c2ed6559afd6795ea2e59d) (Version: 1.0.0.0) FS25_horschJoker4CT
Available mod: (Hash: ed8d3f529710ef680365103552637bbb) (Version: 1.0.0.0) FS25_horschTerrano3FX
Available mod: (Hash: 006fef07e1fd493e0ca65ee2d919f2d7) (Version: 1.0.0.0) FS25_hudToggle
Available mod: (Hash: d8b837ff83d2f803304ba2b495d0ff29) (Version: 1.0.1.0) FS25_InfoDisplayExtension
Available mod: (Hash: 3562e6f97eff646cde64760748dfae2a) (Version: 1.0.0.0) FS25_johnDeerePlanter1775NT
Available mod: (Hash: 500ea3785ebe98a197fa634b9922d518) (Version: 1.0.0.0) FS25_johnDeereSeries4755
dataS/character/playerAnimations/animationsPedestrians.i3d (30.93 ms)
Available mod: (Hash: 36e35e464e54fe7d728258e1117467f8) (Version: 1.0.0.0) FS25_johnDeereSeries7810
Available mod: (Hash: 0185700770ebd4f0a8e5f461881c9075) (Version: 1.0.0.0) FS25_johnDeereT560Pack
Available mod: (Hash: 8b64e93ba3fd03bac3371cc13405808d) (Version: 1.0.0.0) FS25_johnDeereXUV865M
Available mod: (Hash: 789ba36f18472e3487117ec4d3bbff3e) (Version: 1.0.0.0) FS25_kuhnDC401
Available mod: (Hash: 1ce0acb266441c07c93d2d0bbe0e6cec) (Version: 1.0.0.0) FS25_kuhnGF8712
Available mod: (Hash: cad2b29c30036a2f367ecadead5db8b1) (Version: 1.0.0.0) FS25_kuhnGMD4411
Available mod: (Hash: 93a7bacdbfa93b6c86776756d7653389) (Version: 1.0.0.0) FS25_kuhnMergeMaxx950
Available mod: (Hash: 2875347c260f8e5eb7428b7b51421658) (Version: 1.0.0.0) FS25_kuhnVenta4030
Available mod: (Hash: 6630c19ff9e968b6946eaee765ed0096) (Version: 1.0.0.0) FS25_kvernelandEnduroPro5000F
Available mod: (Hash: 5393599510a140aa550f601a32e2dfde) (Version: 1.0.0.0) FS25_kvernelandQualidiscPro
Available mod: (Hash: 10b29b94d9701656c22885901142e73a) (Version: 1.0.0.0) FS25_MMS_Gewichte
Available mod: (Hash: 74bf55fde1109c65223f75b72faac7ca) (Version: 1.0.0.0) FS25_noMoreAutoLift
Available mod: (Hash: e7897eb2e27615d6d3337112527848b7) (Version: 1.0.0.0) FS25_nordstenNS3030
Available mod: (Hash: 7080cca7446bd300367d258c96262e38) (Version: 1.0.0.0) FS25_ObjectBaleStorage
Available mod: (Hash: 6681a2a0324e70cb5bb1f550045d07ad) (Version: 1.0.0.1) FS25_paintAndTerraformAnywhere
Available mod: (Hash: 1937896a063e2ec4c93a5735be813883) (Version: 1.0.0.0) FS25_poettingerMowerPack
Available mod: (Hash: d5512514596299360a6063c9ceb714db) (Version: 1.0.0.0) FS25_poettingerSynkro3020
Available mod: (Hash: 9530b2bbfcd4c256ac28d7b9c71c5783) (Version: 1.0.0.0) FS25_poettingerTerradisc3001
Available mod: (Hash: 4266fc66736e21fcfda4497c2f7151ef) (Version: 1.0.0.0) FS25_realClock
Available mod: (Hash: cfafc1ad956079ab9707e466b0425484) (Version: 1.0.0.0) FS25_RefillableIBCTank
Available mod: (Hash: d79b50699807d6cfe20a975f4df24035) (Version: 1.0.0.0) FS25_RounderWrappedRoundbales
Available mod: (Hash: 7d5bcabc2aaae5edc8bf44e295553764) (Version: 1.0.0.0) FS25_SIMDashboard_Interface
Available mod: (Hash: 47a08e6f37b71df59d43d00b88e0cbaf) (Version: 1.0.0.0) FS25_strautmannZelonCFS2501DO
Available mod: (Hash: 32aa4e9e6e3b8aefb4838f840dd68881) (Version: 1.0.0.0) FS25_SuperForce_KingMods
Available mod: (Hash: 4b13a100610865fd4d28b5b4f896deec) (Version: 1.0.0.0) FS25_unlimitedColorConfigurations
Available mod: (Hash: 1fd53e2c9deac7d70b45f2934ae942bb) (Version: 1.0.0.0) FS25_veenhuisPremiumIntegralPack
Available mod: (Hash: 7b63df117610269481f27fee17debdd9) (Version: 1.0.0.0) FS25_volvoFH16Forestry
Available mod: (Hash: 379280536ab961d88f35cbd535717fb5) (Version: 1.0.0.2) SLM_FS25_TractorTriangle

**Comment by 4c65736975** [comment]
Can you send me the whole log file, it is located in the folder "C:\Users\USER_NAME\Documents\My Games\FarmingSimulator2025\log.txt" Of course I mean the log file after trying to save the game (when it crashes)

**Comment by briggz17** [comment]
[log.txt](https://github.com/user-attachments/files/18065914/log.txt)

Sure, maybe it help.

**Comment by briggz17** [comment]
Sry that I make the first report in german... 
The crash actually only occurs when the mod is loaded.

**Comment by 4c65736975** [comment]
I got you

**Comment by briggz17** [comment]
Maybe it's a problem if vehicles are on the map without the "manual unloading" option enabled. I'll test it with a new save game.

**Comment by briggz17** [comment]
Unfortunately that's not the problem, the problem remains

**Comment by briggz17** [comment]
It actually also occurs when only this mod is activated. However, only if you own a vehicle. Saving works on a new map without your own vehicles.

**Comment by briggz17** [comment]
...
2024-12-09 19:16 data/shared/assets/lights/lizard/plateNumberLight03.i3d (2.17 ms)
2024-12-09 19:16 data/shared/assets/beaconLights/lizard/beaconLight07.i3d (1.60 ms)
2024-12-09 19:16 data/vehicles/claas/shared/displays/displays.i3d (1.65 ms)
2024-12-09 19:16 Info: Failed to request rc, HTTP code 0
2024-12-09 19:16 Error: Running LUA method 'onSaveStartComplete'.
dataS/scripts/configurations/ConfigurationUtil.lua:146: attempt to call missing method 'saveToXMLFile' of table
2024-12-09 19:16 Application exit request forced.
2024-12-09 19:16 Application exit request forced.

Same error code

**Comment by rautapiha** [comment]
minulla on sama bugi.
ilmeisesti johtuu siitä kun vuokrakoneita pelissä ja niiden asetuksia ei voi vuokrauksen jälkeen muuttaa.
