### ISSUE TITLE
After saving will crash and delete save file

### ISSUE THREAD

**Issue by SKULLBEAR11** [4c65736975/FS22_ManualDischarge#21]
### Version

1.0.0.7

### Game Version

Farming Simulator 25 (1.2.1.0)

### 👣 Steps to reproduce

Saving file from the ingame modhub version would stop game from completing the saving process this then crashed the game which then had removed the savefile

**Comment by 4c65736975** [comment]
Duplicate [19](https://github.com/VertexFloat/manualDischarge/issues/19)
