### ISSUE TITLE
Chargement partie bloqué à 99%

### ISSUE THREAD

**Issue by FantazzZdev** [4c65736975/FS22_ManualDischarge#4]
Bonjour, 

Nous venons de remarquer mes amis et moi que votre mod cause des dommages sur la sauvegarde. 

Nous avons fais un teste avec manual discharge, après avoir créer une nouvelles sauvegarde nous avons acheté des tracteurs fait quelques bricoles etc....
Le lendemain nous somme revenu sur le serveur, pas de souci nous avons pu rentrer sans problème.
Suite à ça, nous avons acheter une moissonneuse avec l'option "manual discharge" nous avons quitter la partie et en essayant de revenir le chargement bloqué à 99%.
Ensuite nous avons retirer votre mod et nous avons pu rejoindre le serveur sans problème....

Avez vous une idée pour régler le problème car ce mod est juste excellent ce serait dommage que l'on ne puisse plus l'utiliser.

**Comment by 4c65736975** [comment]
> Bonjour,
> 
> Nous venons de remarquer mes amis et moi que votre mod cause des dommages sur la sauvegarde.
> 
> Nous avons fais un teste avec manual discharge, après avoir créer une nouvelles sauvegarde nous avons acheté des tracteurs fait quelques bricoles etc.... Le lendemain nous somme revenu sur le serveur, pas de souci nous avons pu rentrer sans problème. Suite à ça, nous avons acheter une moissonneuse avec l'option "manual discharge" nous avons quitter la partie et en essayant de revenir le chargement bloqué à 99%. Ensuite nous avons retirer votre mod et nous avons pu rejoindre le serveur sans problème....
> 
> Avez vous une idée pour régler le problème car ce mod est juste excellent ce serait dommage que l'on ne puisse plus l'utiliser.

Please [download](https://github.com/4c65736975/manualDischarge/releases/tag/v1.0.0.6) latest version, bug fixed
