### ISSUE TITLE
Error loading 99% Multiplayer 

### ISSUE THREAD

**Issue by Gringo920** [4c65736975/FS22_ManualDischarge#5]
I have a multiplayer game with my friends.
We bought harvesters with this mod and the next day the game was frozen at 99%, when we removed this mod the game was fixed.
Do you know of any solution, the mod is really spectacular to play with my friends, I don't want to delete it.

**Comment by 4c65736975** [comment]
Does this error occur in the latest version? (1.0.0.6)

**Comment by Gringo920** [comment]
Hello! Sorry if my English is bad, I'm using the translator since I'm from Argentina.
The error occurs to me with the latest version of ModHub, a moment ago I checked the version of the mod that I have in ModDesc.xml and it is (<version>1.0.0.5</version>).

**Comment by 4c65736975** [comment]
Download the latest version using the [instructions](https://github.com/4c65736975/manualDischarge#installation) provided and let me know.

> Hello! Sorry if my English is bad, I'm using the translator since I'm from Argentina. The error occurs to me with the latest version of ModHub, a moment ago I checked the version of the mod that I have in ModDesc.xml and it is (1.0.0.5).

**Comment by 4c65736975** [comment]
> Hello! Sorry if my English is bad, I'm using the translator since I'm from Argentina. The error occurs to me with the latest version of ModHub, a moment ago I checked the version of the mod that I have in ModDesc.xml and it is (1.0.0.5).

Please [download](https://github.com/4c65736975/manualDischarge/releases/tag/v1.0.0.6) latest version, bug fixed
